### ISSUE TITLE
Adopt cloud native technologies

### ISSUE THREAD

**Issue by wipxel** [ofpinewood/pineblog#93]
Containerization is playing a crucial part in the way developers and architects build and think about systems. It would be nice if we can host OPW blog on a [docker ](https://www.docker.com/) enabled cluster like [k8s](https://kubernetes.io/) _without having to do the heavy lifting ourselves._ 

That heavy lifting would include:

- creating Dockerfile and docker-compose.yml files for OPW blog components
- creating build pipelines that push the OPW blog images to an image registry

By having OPW blog images on a public image registry like docker-hub, we would open OPW blog to developers who are used to using cloud native tech. Once we have the images on a public registry we would also be able to look into creating reference deployments for k8s, allowing developers to have the platform up and running on their cluster with a single command.

**Comment by petervandenhout** [comment]
The goal of this project never was to create a complete website/UI, it was always meant to be part of something else. The idea is that you have an existing ASP.NET website and by adding the PineBlog nuget packages add a blog to your website. Therefor containerizing PineBlog does not make sense, you should containerize your website..

I'm closing this issue because it is out of scope for the project.
